### ISSUE TITLE
Scikit-learn (sklearn) missing from requirements.txt

### ISSUE THREAD

**Issue by thiippal** [vecto-ai/vecto#23]
Just installed vecto via pip, motivated by the tutorial at LREC 2018.

The installation works, but Scikit-learn (sklearn) seems to be missing from requirements.txt.

This causes some imports to fail, for example:

`from vecto.benchmarks.analogy import Analogy`

results in a ModuleNotFound error.

**Comment by undertherain** [comment]
Thank you @thiippal ! 
We definitely get some bugs left over from vsmlib-embegym merge into vecto, we'll fix this very soon.
